.gitlab-ci.yml

**Медиа**
**Проверки**
**Изменения**
:cl:

Обновлен сборка Gitlab

---

Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml

Изменение цвета света парамедика

Перекрас света парамедика

---

Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml

Добавляет имплант майндшилд офицеру синего щита и магистрату

Долой революционеров нтшных!

---

Resources/Prototypes/Entities/Effects/lightning.yml

Откатил молнии, так как заваливало тесты

Откат молний из-за проваленного теста

---

Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml

Попытка починить невозможность вытащить батарейку из костюма ниндзи (которая возможно и ломала проверку)

Фикс невозможности извлечь батарейку из костюма ниндзи

---

Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactComponent.cs
Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs
Resources/Prototypes/Research/arsenal.yml
Resources/Prototypes/Research/biochemical.yml
Resources/Prototypes/Research/civilianservices.yml
Resources/Prototypes/Research/experimental.yml
Resources/Prototypes/Research/industrial.yml

Было принято решение облегчить жизнь рнд и снизить цены на исследования
Так же баффнуты артефакты

Ребаланс рнд

---

Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
Resources/Prototypes/Entities/Mobs/Species/diona.yml
Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Resources/Prototypes/Entities/Mobs/Species/human.yml
Resources/Prototypes/Entities/Mobs/Species/moth.yml
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
Resources/Prototypes/Entities/Mobs/Species/slime.yml

Долой ссд трупиков от голода.. на больший период конечно

урон от голода теперь не такой резкий  и не убивает за 2 минуты

---

Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/halloween.yml
Resources/Prototypes/ADT/Entities/Clothing/Uniforms/halloween.yml
Resources/Prototypes/Catalog/Cargo/cargo_botany.yml
Resources/Prototypes/Catalog/Cargo/cargo_vending.yml

фикс цен, чтобы не ругалась проверка при арбитраже

фикс цен для арбитража

---

Content.Shared/CCVar/CCVars.cs

Увеличено время ожидания и предупреждения эвакуационного шатла
И убрано бесоебство артефактов в конце раунда

увеличено время ожидания и предупреждения эвакуационного шатла

---

Resources/Prototypes/Roles/Antags/revolutionary.yml

В главы революции перестали набирать по объявлениям

Качественные революционеры

---

Resources/Prototypes/Catalog/Cargo/cargo_botany.yml
Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
Resources/Prototypes/Catalog/Fills/Crates/botany.yml

Добавлена в карго конопля жизни

корректировка цен у карго

---

Resources/Locale/ru-RU/ADT/Reagents/patch_medicine.ftl
Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
Resources/Prototypes/ADT/Reagents/patch_medicine.yml
Resources/Prototypes/ADT/Recipes/Reactions/patch_medicine_recipe.yml
Resources/Prototypes/Catalog/Fills/Lockers/medical.yml

**Добавил 2 новых реагента:** 
Кровоостанавливающая пудра[заживляет травмы в равной объёму вещества пропорции, 1 единица метаболизирует за 4 секунды]
Сульфадиазин серебра[заживляет ожоги в равной объёму вещества пропорции, 1 единица метаболизирует за 4 секунды]
**Изменил реагенты в пластырях**
**Добавил коробку с пластырями в шкаф с медициной и в шкаф парамеда**

Кровоостанавливающая пудра,Сульфадиазин серебра,Пластыри

---

Resources/Prototypes/ADT/Objectives/traitor.yml

Добавлена цель на кражу пистолета гсб
Добавлена цель на кражу карты гп

Новые цели синдиката

---

Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/defib.yml
Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml

Синий щит и Обр больше не может утащить всю станцию целиком

фикс вместительностей некоторых хранилищ

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml

Вернул боргам те законы которые должны у них стоять
Киборгу уборщика поставил законы дрона
Убрал у киборгов ттс

Борги теперь имеются правильный набор законов

---

Resources/Prototypes/ADT/Entities/Objects/Misc/mini_fire_extinguisher.yml
Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml

Исправлена вместительность у коробки для пластырей
Исправлен размер у коробки для пластырей, пластырей, миниатюрного огнетушителя

Маленький фикс вместительности

---

Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
Resources/Prototypes/Catalog/Fills/Crates/botany.yml

Теперь нету 100% шанса конопли жизни в карго
Индустриальный смэс заряжается и отдает энергию лучше

убрал гарант конопли,смэс лучше заряжается и лучше отдает

---

Resources/Prototypes/Reagents/gases.yml

- Отныне Новакиды могут пить свою кровь!
(просто плазма не наносит им урон)

новакидная плазма

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml

Теперь его можно положить в рюкзаки

изменение размеров лазера капитана

---

Resources/Prototypes/Entities/Objects/Specific/Chemistry/chem_bag.yml
Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml

Пора отказаться от действий ноупа

высыпание из сумок

---

Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml

Теперь СМЭС имеет правильный заряд

фикс вместительности смэса

---

Resources/Prototypes/ADT/Entities/Objects/Power/lights.yml

Изменена яркость ламп труб на более менее мягкий цвет

изменение яркости ламп

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

Уменьшение скорости голодания у мышей

фикс аномального голода у мышей

---

Resources/Prototypes/Entities/Mobs/Player/humanoid.yml

Расса дион исключена из списка обр

дионы больше не обр

---

Resources/Locale/ru-RU/ss14-ru/prototypes/body/organs/animal/animal.ftl
Resources/Prototypes/ADT/Vulpkanin/Body/Organs/Vulpkanin.yml
Resources/Prototypes/ADT/Vulpkanin/Body/Prototypes/Vulpkanin.yml

**Изменения**
:cl:
- add: Теперь у расы вульпкан есть своя собственная печень
**Проверки**

Печень Вульпканина

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

**Изменения**
:cl:
- tweak: Значительно увеличил порог при котором происходит распад молей и тараканов на отдельные органы.
**Проверки**

Фикс развала на множество органов у тараканов и молей.

---

Content.Client/Chat/UI/SpeechBubble.cs

**Проверки**
**Изменения**
:cl:
- fix: Вернул отображение того прошлого LOOC чата

Фикс Лоок чата

---

Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs

**Проверки**
**Изменения**
:cl:

Fix spam message

---

Resources/Locale/ru-RU/ADT/access/access.ftl
Resources/Prototypes/ADT/Access/BlueShield.yml
Resources/Prototypes/ADT/Access/Investigator.yml
Resources/Prototypes/ADT/Access/LawDepartament.yml
Resources/Prototypes/ADT/Entities/Structures/Doors/access.yml
Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
Resources/Prototypes/ADT/Roles/Jobs/SecInvestigator/investigator.yml
Resources/Prototypes/Access/misc.yml
Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml

Добавил доступ Офицера Синего Щита, Юридического Департамента, Агента внутренних Дел, Магистрата, Следователя.
Так же добавил им шлюзы с доступами

Добавил новые доступы и шлюзы с ними

---

Resources/Prototypes/ADT/Shark/Species/Shark.yml

**Изменения**
- remove: Убрал расу акул из ротации.
**Проверки**

Минус акулы

---

Resources/Prototypes/ADT/Roles/Jobs/SecInvestigator/investigator.yml

Следователь больше не может стать революционером

добавлен майндшилд следователю сб

---

Resources/Prototypes/game_presets.yml
Resources/Prototypes/secret_weights.yml

Оставил в выборе режимов в опросе секрет, расширку и выживание
Секрет теперь дает либо нюку, либо предателей и с чуть меньшими шансами - зомби и реву

Изменил выбор режимов и вес режимов в секрете

---

Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Revolvers/Syndicate.yml

Больно велика вместимость в 3 патрона за 6 тк

Нерф трости дробовика

---

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/marinne.yml
Resources/Prototypes/Catalog/Bounties/bounties.yml
Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml
Resources/Prototypes/Catalog/Fills/Crates/cargo.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml
Resources/Prototypes/Entities/Structures/Storage/Tanks/tanks.yml

Снизил кулдаун шаттлов
Повысил награды с баунти карго
Понизил цену канистрам с топливом и бакам с любым газом до 100
Дал всем скафандрам базовую защиту от стана в 20%. Некоторые экземпляры получили защиту выше

небольшая переработка карго

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml

Теперь различные ножи наносят урон при метании а не только боевые ножи

Метание ножей теперь не безопасно

---

Resources/Locale/ru-RU/guidebook/chemistry/core.ftl
Resources/Prototypes/ADT/Demon/Mobs/Species/demon.yml
Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml

**Проверки**
**Изменения**
:cl:

фикс материал арбитража

---

Resources/Prototypes/ADT/Tajaran/Species/Tajaran.yml

**Проверки**
**Изменения**
:cl:
- fix: Убрал спонсорку с расы таяр.

Фикс ошибки

---

Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml

Добавлены сопротивление синди киборгу и обычным киборгам
У синди киборга немного больше хп чем у обычного

Бафф синдиборга и обычных киборгов

---

Content.Shared/CCVar/CCVars.cs

Включил маркер на отображение новых игроков
С маркером игроки появляются которые наиграли меньше 320 минут на сервере

Добавление таймера для маркировки новых игроков

---

Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/damage_mod_set.yml

**Проверки**
**Изменения**
:cl:

Очень мелкий фикс

---

Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Battery/battery_gun.yml

**Проверки**
**Изменения**
:cl:
- fix: Анимация в разряженном виде.

Исправил анимацию для X-02

---

Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Battery/battery_gun.yml
Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
Resources/Prototypes/Catalog/Fills/Items/belt.yml
Resources/Prototypes/Entities/Mobs/Species/base.yml

tweak: Пистолет и снаряжение СЩ
tweak: Урон от давления

СЩ и давление

---

Resources/clientCommandPerms.yml

**Проверки**
**Изменения**
:cl:

фикс от визардов

---

Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml

Починка чистобота
Скорее всего он не сможет носить ушки но лучше он будет работать нежели чем носить ушки

Починка чистобота

---

Content.Client/Chemistry/UI/ReagentDispenserBoundUserInterface.cs
Content.Client/Chemistry/UI/ReagentDispenserWindow.xaml
Content.Client/Chemistry/UI/ReagentDispenserWindow.xaml.cs
Content.IntegrationTests/Tests/Chemistry/DispenserTest.cs
Content.Server/Chemistry/Components/ReagentDispenserComponent.cs
Content.Server/Chemistry/EntitySystems/ReagentDispenserSystem.cs
Content.Shared/Chemistry/Dispenser/ReagentDispenserInventoryPrototype.cs
Content.Shared/Chemistry/SharedReagentDispenser.cs
Content.Shared/Containers/ItemSlot/ItemSlotsComponent.cs
Resources/Prototypes/Catalog/ReagentDispensers/beverage.yml
Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
Resources/Prototypes/Entities/Structures/Dispensers/base_structuredispensers.yml
Resources/Prototypes/Entities/Structures/Dispensers/booze.yml
Resources/Prototypes/Entities/Structures/Dispensers/chem.yml
Resources/Prototypes/Entities/Structures/Dispensers/soda.yml
Resources/Prototypes/tags.yml

Ревёртнул ПР визардов на ограниченую химию.

Revert ,,Limited Chem. dispenser''

---

Content.Client/Administration/UI/Tabs/RoundTab.xaml
Resources/Prototypes/ADT/Entities/Objects/Misc/schrodinger.yml

**Проверки**
**Изменения**
:cl:
- add: Добавлена новая кнопка в панель администратора, команда: `delaystart`  -  ставит на паузу лобби.

Add new button in adminpanel

---

Resources/Prototypes/Entities/Structures/Doors/Airlocks/airlocks.yml

нормальные спрайты шлюзов цк, удивительно.

---

Content.Client/NightVision/NightVisionOverlay.cs
Content.Client/NightVision/NightVisionSystem.cs
Content.Shared/Inventory/InventorySystem.Relay.cs
Content.Shared/NightVision/Components/NightVisionComponent.cs
Content.Shared/NightVision/Components/PNVComponent.cs
Content.Shared/NightVision/Systems/NightVisionSystem.cs
Content.Shared/NightVision/Systems/PNVSystem.cs
Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
Resources/Prototypes/Sirena/Actions/NVAction.yml

Система ночного зрения симпл мобам
Система ПНВ (нуждается в доработке)
Проблема:
Только первый надетый объект с PNVComponent даёт действие, остальные - нет

Ночное зрение симпл мобам

---

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Я говорил что не буду трогать нюку, однако элитный скафандр получает менее 10 урона от лазера. Убийственного ребаланса не будет, зато чуть справедливости.

Маленькие изменения защиты скафандров

---

Resources/Prototypes/ADT/Ursus/Entities/Mobs/Player/Ursus.yml
Resources/Prototypes/ADT/Ursus/faction.yml

Урсов больше не бьют турели НТ и питомцы

Фикс факций урсов

---

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
Resources/Maps/Misc/planet_terminal.yml
Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/card_base.yml
Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/poker_chips.yml
Resources/Prototypes/Reagents/medicine.yml

**Проверки**
**Изменения**
:cl:

Фикс фишек для казино

---

Content.Server/Cargo/Systems/CargoSystem.Orders.cs
Content.Server/StationEvents/Events/CargoGiftsRule.cs

Внедрение ПР у визардов, фиксящий доставку подарков от ЦК

Фикс гифтов от карго

---

Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/smes.ftl
Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
Resources/Prototypes/Entities/Structures/Power/smes.yml

Емкость базовых СМЭС увеличена с 8 до 24 МВт
Емкость индустриальных СМЭС увеличена с 80 до 120 МВт

увеличение емкости СМЭС

---

Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml

Чуть потемней стало зрение симпл мобов

---

.gitmodules

**Проверки**
**Изменения**
:cl:

изменен сабмодуль

---

Resources/Prototypes/ADT/Entities/Objects/Misc/mini_fire_extinguisher.yml

:cl:
- fix: фикс мини огнетушителя

фикс мини огнетушителя

---

Content.Server/StationEvents/Events/IonStormRule.cs
Resources/Locale/en-US/station-events/events/ion-storm.ftl
Resources/Prototypes/Datasets/ion_storm.yml

This reverts commit ed997dc5beb794ef1009e75fd3a8344c045d4f37.
Ревёртнула ревёрт ПР-а, который визарды зачем-то ревёртнули
**Проверки**
- [Х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [Х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [Х] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [Х] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
**Изменения**
:cl:
- add: Добавлен расизм!

Revert "remove racism (#23039)"

---

Resources/Prototypes/Reagents/gases.yml

срочный фикс драсков

---

Resources/Prototypes/ADT/Felinid/Mobs/Player/felinid.yml
Resources/Prototypes/ADT/Novakid/Mobs/Player/novakid.yml
Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Player/Tajaran.yml
Resources/Prototypes/ADT/Ursus/Entities/Mobs/Player/Ursus.yml
Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
Resources/Prototypes/Entities/Mobs/Player/kobalt.yml
Resources/Prototypes/Entities/Mobs/Species/base.yml
Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/shadowkin.yml
Resources/Prototypes/SimpleStation14/Species/ipc.yml

Из-за мердж конфликта вторая часть фиксов отдельно
мды

ченджлоги хуня

---

Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/base.yml
Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/species.yml
Resources/Textures/ADT/Mobs/Silicon/Cyborg/parts.rsi/meta.json

**Проверки**
**Изменения**
:cl:

Убираю киборгу Сб спешилл

---

Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/research/disk.ftl
Resources/Locale/ru-RU/xenoarchaeology/artifact-hints.ftl

Локализовал супер технический диск и магнетическую реакцию артефакта, что собственно и написано в заголовке...

Перевод Супер тех диска. Перевод магнетической реакции артефакта

---

Content.Server/Dragon/Components/DragonComponent.cs

Фикс дракона - теперь он не исчезает (на локалке), открывает порталы и все такое

Плохой дракон фикс

---

Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs

Почистил и структуризировал код генокрада. _В ченджлоге не нуждается_ - польза только для удобства кода, для игроков ничего не изменится.
- Удалил ненужные строки из ChangelingSystem и ChangelingSystem.Abilities
- Перенёс некоторые строки из ChangelingSystem в ChangelingSystem.Abilities чтобы избавиться от путаницы
- Структуризировал ChangelingComponent и добавил недостающие регионы
- Переделал появление начальных способностей генокрада, добавил их в ChangelingComponent и сделал для них ActionEntity. Так и не понял, как сделать то же самое для покупных, возможно придётся копаться в системе их покупки

Тех. апдейт генокрада

---

Resources/Locale/ru-RU/criminal records/criminal-records.ftl

[Перевод] перевод интерфейса консоли криминальных записей отдела СБ

---

Resources/Prototypes/Entities/Objects/Fun/pai.yml

Добавил компонент LanguageSpeaker, позволяющий выбрать язык для общения (у пИИ их два - общегалактический и двоичный)
**Проверки**
- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
**Изменения**
:cl:
- add: Добавлен компонент LanguageSpeaker, позволяющий выбрать язык для общения (у пИИ их два - общегалактический и двоичный)

Компонент выбора языков (общегалактический и двоичный) для пИИ

---

Resources/Prototypes/Entities/Mobs/Player/humanoid.yml

```yml
- type: GhostRole
name: ghost-role-information-centcom-official-name
description: ghost-role-information-centcom-official-description
requirements:
- !type:OverallPlaytimeRequirement
time: 72000 # 20h overall
- !type:DepartmentTimeRequirement
department: Command
time: 72000 # 20h
- !type:DepartmentTimeRequirement
department: Security
time: 72000 # 20h
```

Накинул время на гост-роль ПЦк.

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml

Add: добавление бандан в одеждомат. (золотая, серая, военная, коричневая)
**Проверки**

Банданы в одеждомате

---

Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/security_modern.yml

**Проверки**
**Изменения**
:cl:
- fix: Исправлено отображение скафандров в игре на персонаже.

Исправил баг на скафах!!!

---

Resources/Prototypes/ADT/changeling/mobs.yml
Resources/Prototypes/Entities/Objects/Misc/candy_bowl.yml
Resources/ServerInfo/ADT/NewRecipes.xml
Resources/ServerInfo/ADT/Pathologist.xml

**Проверки**
**Изменения**
:cl:
-fix: Пофиксил взятие таблеток из конфетницы - https://discord.com/channels/901772674865455115/1053757139123961977/1221105738315993200
-fix: Добавил недостающий ингредиент в рецепт фаршированной курицы с овощами 
-fix: Пофиксил возможность кушания личинуса у унатхов
-fix: Пофиксил ошибку руководства патологоанатома - https://discord.com/channels/901772674865455115/1053757139123961977/1220819743158833323

Фиксы просьб баг-репорта

---

Resources/Prototypes/Body/Prototypes/drone.yml

- Список изменений:
- Исправлено появление левой руки киборга, в одном из слотов инвенторя дронов,
- Добавлен парт головы киборга дронам,
- Количество правых и левых рук дрона изменено (4 left / 2 right —> 3 left / 3 right),
- Все children рук киборга, перенесены из последовательного соединения друг другом, в общий parent в виде головы киборга
**Проверки**
**Изменения**
:cl: Kivchik
- add: Добавлен парт головы киборга дронам
- tweak: Изменено количество левых и правых рук дрона | Изменён способ присоединения children к parent у партов рук киборга
- fix: Исправлено появление левой руки киборга у всех дронов

(BugFix) Исправление появления при сборке/спавне дрона, левой руки киборга

---

Resources/Prototypes/ADT/tags.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

**Проверки**
**Изменения**
:cl:

тэг для скафандра и обновление секретки

---

Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
Resources/Prototypes/ADT/KD/Channels/Channels/DroneAntagChannel.yml

***Помощь Джунгарику, небольшие доработки к [Пулл-реквесту 523](https://github.com/xtray85/space_station/pull/523)
При запуске локалке заметил мелкие недочёты, решил поправить.***
**Проверки**
**Изменения**
:cl: Schrodinger71
- add: Добавил свой компонент(LevitationAct) на антага-КПБ.
- tweak: Сделал канал дронов-антагов поярче.
- tweak: Добавил тех-панель дронам-антагам.

Небольшие фиксы дронов-антагов Джунгарика

---

Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_InventoryTemplate.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Spawner.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_StartingGear.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Turret.yml

**Проверки**
**Изменения**
:cl:
- add: 
Дал кпб дрону в двух карманах магазины для лазерной и на спине саму винтовку
Сделал звук ходьбы кпб дрона как у сбшного киборга
- fix: 
Исправил спавнеры
Исправил фонари дронов
Звук ударов КПБ и дронов теперь металлический
Поменял урон дронов и КПБ

Фикс и добавления дронам-антагам

---

Resources/Maps/traderpost.yml
Resources/Prototypes/ADT/Entities/Mobs/player/trader.yml
Resources/Prototypes/GameRules/events.yml

Незначительные изменения карты торговцев ТСФ и их товаров
**Проверки**

trader minor update

---

Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
Resources/Prototypes/name_identifier_groups.yml

**Проверки**
**Изменения**
:cl:
- fix: Названия и суффиксы дронов-антагов

Изменение названий дронов-антагов

---

Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_StartingGear.yml

Фикс температуры, реакций на лампочки, модификаторов урона, добавление защиты от радиации, взрывов и стана с помощью невидимого броника в качестве Loadout
**Проверки**
**Изменения**
:cl:
- add:
добавление защиты от радиации, взрывов и стана с помощью невидимого броника в качестве Loadout
- fix:
температуры, 
реакций на лампочки, 
модификаторов урона,

Нормальный фикс дронов-антагов (от последней обновы мастера)

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/chemistry.yml

**Проверки**
**Изменения**
:cl:
- add: 
Добавил крафт пробирки в Медицинском ТехФабе и добавил его в список доступных крафтов

Создание крафта пробирки в Медицинском ТехФабе и его добавление туда

---

Resources/Prototypes/Entities/Structures/Power/smes.yml

Аномальные значения потребления и энергоотдачи наверное вызывают мигания света,данный пр проверит так ли это на самом деле
(Проверенно на деве,там вроде нормально было)

Возможная починка света

---

Resources/Prototypes/Catalog/uplink_catalog.yml

Убрал даблу из аплинка

---

Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/case.yml

**Проверки**
**Изменения**
:cl:
- tweak: Размер портсигар

Изменил размер портсигар

---

Content.Client/Clothing/Systems/WaddleClothingSystem.cs
Content.Client/Movement/Systems/WaddleAnimationSystem.cs
Content.Shared/Clothing/Components/WaddleWhenWornComponent.cs
Content.Shared/Movement/Components/WaddleAnimationComponent.cs
Resources/Prototypes/Entities/Clothing/Shoes/specific.yml

**Проверки**
**Изменения**
:cl: COTE_LAPYX
- add: Добавлена анимация ходьбы в клоунских туфлях.
https://github.com/xtray85/space_station/assets/107066700/18b86cb1-ca4c-4940-9023-605a6c7ae883

теперь при одетых ботинках клоуна изменяется анимация ходьбы.

---

Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
Resources/Prototypes/game_presets.yml
Resources/Prototypes/secret_weights.yml

Добавил отдельные режимы с генокрадами:
1. Предатели и генокрады
2. Ядерные оперативники и генокрады
3. Революционеры и генокрады
4. Зомби и генокрады
5. Генокрады
**Проверки**

Changeling game presets

---

Content.Server/Speech/Components/NyaAccentComponent.cs
Content.Server/Speech/EntitySystems/NyaAccentSystem.cs
Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/orientalears.yml
Resources/Prototypes/ADT/Felinid/Mobs/Player/felinid.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Resources/Prototypes/Entities/Clothing/Head/misc.yml

обновила акцент фелинидов и ушек
оригинальный ПР: https://github.com/Workbench-Team/space-station-14/pull/1
**Проверки**
**Изменения**
:cl:

фелинид апдейт

---

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs

увеличение размера шаттла под фтл-полеты

---

Resources/Prototypes/Catalog/uplink_catalog.yml
Resources/Prototypes/Research/experimental.yml

**Проверки**
**Изменения**
:cl:

уменьшение цены жилета

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml
Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Resources/Prototypes/Entities/Mobs/Player/silicon.yml

**Проверки**
**Изменения**
:cl:

Типо... Поменял что-то у боргов с RobotTalk на BorgTalk..

---

Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml

Моль теперь может есть виноград
**Проверки**
**Изменения**
:cl:
- fix: Исправлено кушание винограда у моли

моль может кушать виноград

---

Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml

на зимней куртке теперь можно надеть капюшон
**Проверки**
**Изменения**
:cl:
- fix: Исправлено надевание капюшона для зимней куртки

капюшон для куртки

---

.github/workflows/build-test-debug.yml
.github/workflows/test-packaging.yml
.github/workflows/yaml-linter.yml
global.json

Временное решение проблем с github actions. После апстрима нужно будет откатить эти изменения.
Этот PR заставляет github actions (yaml-linter, test-packaging, build-test-debug) использовать dotnet 8.0.203 и отключает rollForward версий dotnet в global.json. Если не откатить эти изменения, после апстрима могут возникнуть проблемы со сборкой.
**Проверки**

Временное решение проблем с github actions.

---

Resources/Prototypes/ADT/Lavaland/NPCs/AshWalker/AshWalker.yml
Resources/Prototypes/ADT/Lavaland/NPCs/BaseHumLavalandMob.yml

Поправлен баг с метаболизмом пеплоходцев. 
Пеплоходцы теперь говорят на языке унати

Поправил баг с неусвоением пищи у пеплоходцев

---

Resources/Prototypes/ADT/Entities/Mobs/anomally_abomination.yml

**Проверки**
**Изменения**
:cl:
- add: В anomally_abomination.yml добавлена основа ADTBaseMobAbomination в которой изменён компонент "StatusEffects"
- tweak: Теперь все мобы в anomally_abomination.yml наследуют ADTBaseMobAbomination

Удаление мобам "Мерзости" c экспедиции возможности сна

---

Resources/Prototypes/ADT/Maps/ADTMaps/atlas.yml
Resources/Prototypes/ADT/Maps/ADTMaps/avrite.yml
Resources/Prototypes/ADT/Maps/ADTMaps/box.yml
Resources/Prototypes/ADT/Maps/ADTMaps/cluster.yml
Resources/Prototypes/ADT/Maps/ADTMaps/delta.yml
Resources/Prototypes/ADT/Maps/ADTMaps/europa.yml
Resources/Prototypes/ADT/Maps/ADTMaps/fland.yml
Resources/Prototypes/ADT/Maps/ADTMaps/meta.yml
Resources/Prototypes/ADT/Maps/ADTMaps/origin.yml
Resources/Prototypes/ADT/Maps/ADTMaps/packed.yml
Resources/Prototypes/ADT/Maps/ADTMaps/saltern.yml

В этом ПРе добавлена роль юриста на все карты
**Проверки**
**Изменения**
:cl:
- add: Добавлена роль юриста на картах

роль юриста на картах

---

Resources/Prototypes/lobbyscreens.yml

**Проверки**
**Изменения**
:cl:
- add: Добавлены лобби экраны

Лобби экраны

---

Content.Client/Overlays/EntityHealthBarOverlay.cs
Resources/Credits/ADTeam.txt

Исправление видимости полосок здоровья у невидимых существ, и вписал в credits ADT
**Проверки**
**Изменения**
@FaDeOkno @Nekodar <3
:cl: Schrodinger
- fix:  Визоры охранные, медицинские, расширенные больше не палят невидимок.

Попытка фикса визора

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Reverts xtray85/space_station#744

Revert "Возвращаем крафт мех фабрикатора"

---

Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml

- add: Добавлен майндшилд оператору центкома и членам обр

addded Mindshield for centcom and ert

---

Resources/Prototypes/ADT/Entities/Clothing/Head/hats.yml

Теперь нианы могут съесть берет Старшего Инженера
**Проверки**
**Изменения**
:cl: Torgovec
- fix: Исправление непригодного для питания нианов берета СИ

fixed eating beret CE

---

Content.Server/ADT/Hemophilia/HemophiliaSystem.cs
Content.Server/Body/Components/BloodstreamComponent.cs
Content.Shared/ADT/hemophilia/HemophiliaComponent.cs
Resources/Locale/en-US/ADT/traits/traits.ftl
Resources/Locale/ru-RU/ADT/traits/disabilities.ftl
Resources/Prototypes/ADT/Traits/neutral.yml

Добавление такой черты как ГЕМОФИЛИЯ
У персонажа с гемофилией практически не будет сворачиваться кровь
Спасибо огромное Коте за обучение созданию систем

Добавление гемофилии
